# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: mkdir /tmp/nextflow && cd /tmp/nextflow && wget -qO- get.nextflow.io | bash && ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  displayName: 'nextflow install'
- script: nextflow -v
  displayName: 'nextflow version'
