trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'rpd-sg10k-grch38-gatk4-gvcf-freebayes-vcf:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: mkdir /tmp/nextflow && cd /tmp/nextflow && wget -qO- get.nextflow.io | bash && sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  displayName: 'nextflow install'
- script: nextflow -v
  displayName: 'nextflow version'
- script: nextflow main.nf -test
  displayName: 'nextflow syntax check on main.nf'
# FIXME functional tests with nextflow and docker go here
